### ISSUE TITLE
TODO list for OCUS

### ISSUE THREAD

**Issue by harrieklomp** [opencaching/opencaching-pl#2013]
To prevent there are many issues about immigrating Polish code to OCUS i suggest to all to add here what has to be done and to be solved to make it to a success. If you like to add or solve something, just add it and add your name to it :-)

- [ ] Make top menu including some site specific articles pages. Can be done with specific links in menu. (Harrie)
- [ ] Add welcome text. This should be done with OCUS admins. (Harrie)
- [ ] Make Geopath work with settings desired by OCUS admins. (Harrie)
- [ ] Add mascot to system.
- [ ] Add specific US items to left menu. (Harrie)
- [ ] setup of cron jobs (Andrei)
- [ ] French and Spanish translations. We need Spanish translator (Harrie)
etc, etc

**Comment by andrixnet** [comment]
Almost ready for production release of new site, albeit with some known issues still to work on.

**Comment by kojoty** [comment]
@andrixnet where is the complete list of issue (is this list above complete and updated?)
Thanks @andrixnet for all your work in this mater :)

**Comment by andrixnet** [comment]
The list here contains many management and administrative tasks related to the migration process, in addition to the code development tasks. 
Most of the actual development issues are listed here: https://github.com/opencaching/opencaching-pl/projects/5 and here https://github.com/opencaching/opencaching-pl/milestone/1 and here https://github.com/opencaching/opencaching-pl/labels/OCNA%20migration
(I think they partly overlap, partly complete each other.)
-----------------------------------------
Main site is up and operational at http://www.opencaching.us (Aruba small VPS)
Still TODO: set up SSL certificates and configuration.
Email subsystem up and running.
Secondary sites up and running.
-----------------------------------------
Several configuration and user roles/rights still need to be configured. 
Some small details I managed already to sovlew directly. 
I am in constant contact with our american friends.

**Comment by andrixnet** [comment]
@kojoty when you have the time, please first take a look at https://github.com/opencaching/opencaching-pl/pull/2069 

This paves the way for the first time unified attributes between OCPL sites (and first step to move attribute definitions to code). Also the proper updates have been prepared for OKAPI and a corresponding pull request is pending there. 

Attributes are now well documented here https://wiki.opencaching.eu/index.php?title=Cache_attributes
I am also in contact with c:geo developers to support the complete OC attribute set.

Next step after this PR will be to add/remove some attribs at NL, RO, UK, US according to individual requests from each OC site team.

Once completed, **all OCPL based sites** will have a consistent and well document set of attributes.

**Comment by andrixnet** [comment]
Updated OCNA database contents regarding caches and cache types. 
Using newly designed IDs, documented (work in progress) [here](https://wiki.opencaching.eu/index.php?title=Cache_types). 

ID 8 (moving) -> ID 9
ID 9 (podcache) -> ID 1 other + MP3 attribute
ID 10 (guestbook) -> ID 23
ID 11 (usb) -> ID 1 other + USB attribute
ID 12 (bitcache) -> ID 24
ID 13 (letterbox) -> ID 1 + letterbox attribute.

Please note that I've used the new attribute ID assignments as documented [here](https://wiki.opencaching.eu/index.php?title=Cache_attributes) which are work in progress, to be deployed soon. Until then, there will be some inconsistency due to missing or wrong IDs in the database. 

This is a preparation phase part of OCNA migration. The site will continue to exhibit inconsistent behaviour regarding these cache types, which will be solved when work on #2024 and #860 are finalized.

All caches turned into "other type" + attribute will need to be revised by their owners (after cache type and attribute work is complete) to assign them the correct type if different from "other".

Caches affected by these inconsistencies (at this time): ~ 150 caches total.

**Comment by paulshannon** [comment]
@andrixnet I'd like to help with the OCNA instance specifically. Is there a migration still in the works to bring it up to date?

Feel free to contact by email if that is easier for you. Thanks! paul at paulshannon.ca

**Comment by andrixnet** [comment]
Interim solution for OCNA cache types. Upon agreement with North America OC-Team, caches of still undefined/unimplemented types to be redefined as type=unknown and with an attribute added. 
- US Benchmark - attribute exists (attr_id=208)
- BITcache - new attribute (temporary attr_id=99301)
- Guestbook - new attribute (temporary attr_id=99302)
- Challenge - new attribute (temporary attr_id=99303)

Note: these attributes are being added to the database and corresponding images created and deployed to make them functional. No additional implementation is done (like specifics for GPX export, etc) for them.

Caches of unsupported types become "UNKNOWN" and receive an additional attribute.

**Comment by andrixnet** [comment]
Example: OU04C5 https://www.opencaching.us/viewcache.php?wp=OU04C5
Was type=guestbook.
New type=other
New +++attrib guestbook
