### ISSUE TITLE
GeoPath FINAL cache type

### ISSUE THREAD

**Issue by andrixnet** [opencaching/opencaching-pl#2076]
There is a currenttly unused (dropped) cache type : type 8 (podcache). 
This has already been partially redefined as GeoPath FINAL (todo). 
Currently it is/seems unused and by default not allowed, also it still features the old podcache graphics. 

The purpose of this issue is to track the complete  implementation of GeoPath FINAL cache type.

### Stage 1
- [ ] cache type definition - in code
- [ ] cache type definition - in database (as it still exists and is used)
- [ ] remove old podcache data
- [ ] update database contents, all caches with ID 8 => ID 1 (other) + MP3 attribute
- [ ] create new graphics for this type
At this point the cache type is properly defined. Type remains disabled by default.

### Stage 2
- [ ] define the workings of this cache type
- [ ] implement the corresponding code
- [ ] enable the type on production servers (where geopath module is active)

**Comment by andrixnet** [comment]
Assigning myself for stage 1 as part of https://github.com/opencaching/opencaching-pl/issues/2024 and https://github.com/opencaching/opencaching-pl/issues/860

**Comment by kojoty** [comment]
BTW: I think that there is no reason for geopath final - in my opinion this type is generally useless.

**Comment by andrixnet** [comment]
If such a type is deemed useless, no problem. I'll make the changes so that it is not included. 
Please close this as WON'T FIX if this type should not be implemented.

**Comment by kojoty** [comment]
but we need to be sure that this is removed from the rest of the code... - please let it be open for now.

**Comment by deg-pl** [comment]
I think we should to remove "geopath final" from OC code.

**Comment by andrixnet** [comment]
Removal in progress

**Comment by andrixnet** [comment]
Removed at https://github.com/andrixnet/opencaching-pl/tree/cache_type

Please see https://github.com/opencaching/opencaching-pl/issues/860#issuecomment-508733416 for remaining details.

**Comment by andrixnet** [comment]
Database contents update is designed to work in conjunction with Refactoring attributes PR (uses new attrib ID).
